### PR TITLE
Add jyotimahapatra to approvers/reviewers

### PR DESCRIPTION
**Pull request by nckturner**

### CODE REVIEW

**Comment by nckturner** [comment]
@jyotimahapatra can you add yourself to the kubernetes-sigs org?  It can be done via PR if you are already a member of the kubernetes org.

**Comment by nckturner** [comment]
See https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem

**Comment by jyotimahapatra** [comment]
@jyotimahapatra is part of kubernetes-sigs now https://github.com/kubernetes/org/pull/3253/files

**Pull request merged**
