### PR TITLE
chore: Update CLI dependencies `cobra` and `viper`

### PR DESCRIPTION
**Pull request by bryantbiggs**
**What this PR does / why we need it**:
- Update CLI dependencies `cobra` and `viper` to latest; reduces the number of transitive dependencies and patches vulnerabilities

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by wongma7** [comment]
/lgtm
/approve

will need rebase on https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/687 and https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/706

**Comment by bryantbiggs** [comment]
cc @wongma7

**Comment by wongma7** [comment]
> An error occurred (NoSuchEntity) when calling the DeleteRole operation: The role with name aws-iam-authenticator-test-role-KubernetesAdmin cannot be found. 

seems the role name gets reused and tests race each other.

**Pull request merged**
