### PR TITLE
Add a counter for API server watch failures

### PR DESCRIPTION
**Pull request by nckturner**
- New metrics package
- Use new registry in test setup to avoid duplicate metric registration

Replaces: #387

### CODE REVIEW

**Comment by wongma7** [comment]
expose the metrics over http?

https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/promauto

func main() {
        go Random()
        http.Handle("/metrics", promhttp.Handler())
        http.ListenAndServe(":1971", nil)
}

**Comment by wongma7** [comment]
or i guess they are already exposed but show a curl example  : D

**Comment by nckturner** [comment]
With MountedFile: 
```
$ curl -k https://localhost:21362/metrics | grep "configmap_watch_failures"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                            
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                                              
100  7915    0  7915    0     0   # HELP aws_iam_authenticator_configmap_watch_failures EKS Configmap watch failures                                                                                       
85# TYPE aws_iam_authenticator_configmap_watch_failures counter                                                                                                                                            
8aws_iam_authenticator_configmap_watch_failures 0                                                                                                                                                          
k      0 --:--:-- --:--:-- --:--:--  858k        
```

And with EKSConfigMap, but API server not running, after a few seconds: 
```
$ curl -k https://localhost:21362/metrics |grep "configmap_watch_failures"                                                                            [22:53:08]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                            
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                                              
100  6416    0  6416# HELP aws_iam_authenticator_configmap_watch_failures EKS Configmap watch failures                                                                                                     
  # TYPE aws_iam_authenticator_configmap_watch_failures counter                                                                                                                                            
  aws_iam_authenticator_configmap_watch_failures 2                                                                                                                                                         
```

**Pull request merged**
