### PR TITLE
Update token_test.go

### PR DESCRIPTION
**Pull request by surki**
Remove deprecated package, not available in client-go v0.24.0

### CODE REVIEW

**Comment by surki** [comment]
@nckturner @wongma7 can you please check this PR?

**Review by jaypipes — APPROVED** [review]
:+1:

**Comment by surki** [comment]
@nckturner can you please take a look at this?

This is blocking our upgrade, had to maintain a forked copy for this small change.

**Comment by kinarashah** [comment]
@wongma7 @nckturner Apologies for retagging, would it be possible to add ok-to-test label and get this merged?

**Comment by surki** [comment]
Looks like the same changes are merged via another PR #474 
thanks @nckturner 

btw, wondering if there is some kind additional communication somewhere one has to do  to get the PRs reviewed here.

**Pull request closed without merging**
