### PR TITLE
create new release 0.6.25

### PR DESCRIPTION
**Pull request by modulitos**
**NOTE:** Merge this PR AFTER this PR has been merged: https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/747

**What this PR does / why we need it**:

Create a new tag and release

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # N/A

### CODE REVIEW

**Comment by micahhausler** [comment]
/hold
/lgtm
/approve

@modulitos just add an unhold comment when you're ready to merge this

**Comment by modulitos** [comment]
Re-added the version bump

**Comment by micahhausler** [comment]
There we go
/lgtm
/approve

**Pull request merged**
