### PR TITLE
Create hello.txt

### PR DESCRIPTION
**Pull request by jku8**
Hi Logan, I am a PM on the EKS team at AWS. We are looking into pain points for AWS Identity Center/SSO users who also use EKS. I saw your PR here https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/416. Would you be interested in hopping on a cal to chat a bit on this issue?

### CODE REVIEW

**Comment by jku8** [comment]
This PR was just to communicate with you @logandavies181

**Comment by logandavies181** [comment]
Hey @jku8 - interesting choice of communication :). I'm `@Logan Davies` on kubernetes slack - if that's easier?

My employer has Enterprise Support, so maybe it's worth reaching out through our SA/TAM? I'd be happy to share more details via PM or direct email

**Comment by nckturner** [comment]
Please reach out over slack, don't us pull requests as a method to communicate.

**Pull request closed without merging**
