### PR TITLE
Update aws-sdk version to 1.16.13, which includes support for credential_process and getting credential expiration

### PR DESCRIPTION
**Pull request by llamahunter**
credential_process, introduced in version 1.16.0.

Basically, ran `dep ensure -update github.com/aws/aws-sdk-go`, did a build, and checked that it now worked with credential_process.

### CODE REVIEW

**Comment by llamahunter** [comment]
signed the contributor agreement.

**Comment by llamahunter** [comment]
Hmm... it's odd that Gopgk.toml didn't get updated by `dep ensure`.  Yet `dep check` returns no errors.

**Comment by llamahunter** [comment]
Any chance this could get pulled soon and a new release published?  I am having to distribute custom binaries to my team for the time being, and would rather people use an official release.

**Comment by nckturner** [comment]
@llamahunter yes, we can get this in the next release.  Appreciate the PR.

**Comment by llamahunter** [comment]
So, https://github.com/aws/aws-sdk-go/pull/2375 got merged, adding support for getting the credential expiration time, and released as 1.16.13, so pulling that into this pull request as well.

Same process used.  Just ran `dep ensure -update github.com/aws/aws-sdk-go`

**Comment by llamahunter** [comment]
@nckturner Any chance this could get pulled soon?  Not sure if @mattmoyer is watching his PR queue.

**Comment by llamahunter** [comment]
Trying not to be a pain, but would really like to get this aws-sdk-go version update pulled in so that I can create a pull request for token caching.

**Comment by llamahunter** [comment]
Ping.  Please accept this pull, or upgrade the aws-sdk-go library version to 1.16.13 in some other way, ASAP.

**Comment by llamahunter** [comment]
Hey @mattmoyer and/or @nckturner, any chance this can get pulled soon?  Not sure how else to contact you except via comments on this pull request :-/.

**Comment by azman0101** [comment]
This is a question about credential_process support: 

```
AWS_PROFILE=xxxxx-staging aws-iam-authenticator-0.5.0 token -i ps.aws.xxx-france.fr -r "arn:aws:iam::249602288yyyy:role/K8SAdmin"
could not get token: ProcessProviderExecutionError: error in credential_process
caused by: exit status 1
```

my config file:
```
[profile xxxxx-staging]
region = eu-central-1
credential_process = "/usr/local/bin/get-aws-credentials-cli" 249602288yyyy
```

The script get-aws-credentials-cli  generate outputs like this one:
```
{
  "Version": 1,
  "AccessKeyId": "an AWS access key",
  "SecretAccessKey": "your AWS secret access key",
  "SessionToken": "the AWS session token for temporary credentials",
  "Expiration": "ISO8601 timestamp when the credentials expire"
}
```
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

And this script is working fine with awscli
```
AWS_PROFILE=xxxxx-staging aws sts get-caller-identity
{
    "UserId": "AROAXXXXXXXXXXX:vault-ldap-xxxxxxxx-manage-249602288yyyy-3584892511-1344",
    "Account": "249602288yyyy",
    "Arn": "arn:aws:sts::799602488836:assumed-role/K8SAdmin/zzz-kkk-xxxxxxxx-manage-249602288yyyy-3584892511-1344"
}
```
I'm wondering `aws-iam-authenticator` is supporting `credential_process` ?

**Pull request merged**
