### PR TITLE
solve the problem that client-go cannot find v1alpha1 after upgrading to 0.24

### PR DESCRIPTION
**Pull request by fengshunli**
reference link https://github.com/fengshunli/aws-iam-authenticator/tree/main

### CODE REVIEW

**Comment by sppwf** [comment]
Hi Guys,

Any status on this?

Thanks
Sergiu Plotnicu

**Comment by fengshunli** [comment]
@nckturner look at this pr

**Comment by micahhausler** [comment]
Hi @fengshunli, Can you please provide more details about the issue you're facing?  As-is, I don't think this PR solves any v1alpha1 problems, as the latest release (v0.5.9) defaults to returning v1beta1 output unless the kubeconfig explicitly specifies v1alpha1. 

Have you updated your kubeconfig to use the v1beta1 API? If you're getting v1alpha1 not found errors from kubectl, that is a kubeconfig issue, and the request never even gets to aws-iam-authenticator.

Have a look at a [similar change to the AWS CLI](https://github.com/aws/aws-cli/pull/6940) for more context on this issue

**Comment by fengshunli** [comment]
@micahhausler this is an import error caused by the introduction of k8s.io/client-go v0.24.3

**Comment by tigrato** [comment]
Is it possible to merge this PR?

**Comment by nckturner** [comment]
Sorry for the delay

/lgtm
/approve

**Pull request merged**
