### PR TITLE
Pull the response body so we can log it if there's an error

### PR DESCRIPTION
**Pull request by jbell-shibumi**
Signed-off-by: Johnathan Bell <johnathan.bell@shibumi.com>

Added response body logging for better diagnosis of issues.  Based on v0.1.0 tag

### CODE REVIEW

**Comment by christopherhein** [comment]
Seems like a reasonable addition.

**Comment by nckturner** [comment]
I think it could be helpful to have response body as an optional field to print to logs, but it would be too much if we are unable to turn it off.  Would you like to make that fix and rebase on master @jbell-shibumi?

**Comment by jbell-shibumi** [comment]
Let me see what i can do @nckturner -- I'm not that familiar with golang...

**Comment by mattlandis** [comment]
Closing due to inactivity.  Feel free to reopen or open new PR with the issues addressed.

**Pull request closed without merging**
