### PR TITLE
Update upstream dependencies to v1.31.0

### PR DESCRIPTION
**Pull request by shizuchanw**
**What this PR does / why we need it**:
Cherry-picked [commit on master to update upstream dependencies to v1.31.0](https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/c8f39c5353b53550ee81cf194ec18c5b9415e04c)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # N/A

### CODE REVIEW

**Comment by shizuchanw** [comment]
@jyotimahapatra @micahhausler Can I get an approved label? Thank you!

**Comment by bryantbiggs** [comment]
FYI - if you want to release this, you'll need to bump the version https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/af0516881f230fff185217e13ea1874931159fe6/version.txt#L1

otherwise, this is just adding the commit to the 0.6 branch (no release)

**Comment by shizuchanw** [comment]
> FYI - if you want to release this, you'll need to bump the version
> 
> https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/af0516881f230fff185217e13ea1874931159fe6/version.txt#L1
> 
> otherwise, this is just adding the commit to the 0.6 branch (no release)

Thank you! Was gonna do it in a different PR but I guess it makes more sense to keep it in the same PR and add a new commit, just updated version.txt

**Comment by shizuchanw** [comment]
> @jyotimahapatra @micahhausler Can I get an approved label? Thank you!

bump

**Pull request merged**
