### PR TITLE
goreleaser: bump release to 0.164.0 and fix config deprecations

### PR DESCRIPTION
**Pull request by antoinedeschenes**
Required groundwork for Graviton and darwin arm64 support

Signed-off-by: Antoine Deschênes <antoine@antoinedeschenes.com>

### CODE REVIEW

**Comment by antoinedeschenes** [comment]
Still need to add golang 1.16, arm64 platform and multiarch docker images after this, would you rather have it in a single PR?

**Comment by nckturner** [comment]
Sorry for the delay, either is fine but we can do a separate PR to keep it simple.

**Pull request merged**
