### PR TITLE
[1/2] Release 0.5.4

### PR DESCRIPTION
**Pull request by jyotimahapatra**
Release v0.5.4
* Embed go-runner into the image ([#426](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/426), @jyotimahapatra)
* Bump Go to 1.17 in Travis ([#414](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/414), @gliptak)
* Build multi-arch images ([#417](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/417), @glebiller)
* Add kind-based development environment ([#422](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/422), @nckturner)
* Add jaypipes to approvers/reviewers ([#407](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/407), @nckturner)
* Fix deps ([#396](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/396), @frioux)
* Fix panic when cache file can't be Stat-ed ([#410](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/410), @sarahhodne)
* Fix missing status definition in v1 CRD ([#411](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/411), @rifelpet)
* Use ./hack/install-etcd.sh ([#405](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/405), @nckturner)
* Run integration tests with per-test role ([#402](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/402), @nckturner)
* Add a counter for API server watch failures ([#400](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/400), @nckturner)
* Upgrade CRD manifest to v1 ([#397](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/397), @rifelpet)
* Move inactives to emeritus_approvers and add active users ([#399](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/399), @nckturner)
* Fix tests add vendor ([#398](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/398), @nckturner)
* Integration test framework ([#395](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/395), @nckturner)
* Add cloudbuild & improvements ([#394](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/394), @nckturner)
* Fix typo ([#390](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/390), @shyr)
* *: add user/role subcommands ([#381](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/381), @gyuho)
* goreleaser: bump release to 0.164.0 and fix config deprecations ([#371](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/371), @antoinedeschenes)
* Run go mod vendor ([#388](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/388), @nckturner)
* doc: fix typo in RELEASE.md ([#376](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/376), @stig)
* [pkg/token]: Update credential API version ([#386](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/386), @micahhausler)
* Enrich Audit Logs with additional AWS Identity details (via audit logs' "extra" map) ([#372](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/372), @adrianosela)

### CODE REVIEW

**Comment by jyotimahapatra** [comment]
@nckturner Updatd the changelog with the latest commits. I think this is good to go now

**Comment by nckturner** [comment]
Thanks @jyotimahapatra.  I realized there is one thing we need to do.  Can you separate the changes to `deploy/example.yaml` into a separate PR and label this one [1/2] and the example changes [2/2]?  That way we can tag this release, and then do the build, publish the image, and update the yaml. Otherwise have a period of time where the docs are broken.

**Comment by jyotimahapatra** [comment]
@nckturner  done

**Pull request merged**
