### PR TITLE
Remove misc files that are no longer used

### PR DESCRIPTION
**Pull request by bryantbiggs**
**What this PR does / why we need it**:
- Remove unused empty file and travis CI (no longer used)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by bryantbiggs** [comment]
well thats a bummer

**Comment by wongma7** [comment]
/lgtm
/approve

will need rebase on https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/687 and https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/706

**Comment by bryantbiggs** [comment]
Cc @wongma7

**Pull request merged**
